<script setup>
import { ref, onMounted, computed } from 'vue'
import {
  PhInfo,
  PhLaptop,
  PhUploadSimple,
  PhMusicNotes,
  PhFileAudio,
  PhSpeakerHigh,
  PhTrash,
  PhMicrophone,
  PhX
} from '@phosphor-icons/vue'
import { useToast } from 'primevue/usetoast'
import api from '../services/api'
import BaseCard from '../components/base/BaseCard.vue'
import BaseBtn from '../components/base/BaseBtn.vue'
import BasePageHeader from '../components/base/BasePageHeader.vue'
import BaseModal from '../components/base/BaseModal.vue'

const toast = useToast()

// State
const activeTab = ref('tts') // Default to TTS
const isLoading = ref(false)
const error = ref(null)

// --- TTS State ---
const ttsText = ref('')
const ttsStatus = ref(null)
const ttsEngine = ref('gtts')

// --- Audio Library State ---
const audioFiles = ref([])
const isDragging = ref(false)
const fileInput = ref(null)

// ===================== COMPUTED =====================
const filteredFiles = computed(() => {
  return audioFiles.value
})

// ===================== LIFECYCLE =====================
onMounted(async () => {
  await fetchAudioFiles()
})



// ===================== TTS ACTIONS =====================
const speakText = async () => {
  if (!ttsText.value) return
  
  // OS / Browser TTS
  if (ttsEngine.value === 'os') {
    if (!('speechSynthesis' in window)) {
      error.value = 'Text-to-speech is not supported in this browser.'
      return
    }
    
    // Stop any existing speech
    window.speechSynthesis.cancel()
    
    const utterance = new SpeechSynthesisUtterance(ttsText.value)
    
    // Setup event handlers
    utterance.onstart = () => {
      ttsStatus.value = 'Playing (Local)...'
    }
    
    utterance.onend = () => {
      ttsStatus.value = 'Played successfully'
      setTimeout(() => { ttsStatus.value = null }, 3000)
    }
    
    utterance.onerror = (e) => {
      console.error('TTS Error:', e)
      error.value = 'Local playback failed'
      ttsStatus.value = null
    }
    
    // Speak
    window.speechSynthesis.speak(utterance)
    return
  }

  // Google TTS (Server)
  try {
    isLoading.value = true
    error.value = null
    ttsStatus.value = 'Generating audio...'
    // Call API (playOnLaptop = false)
    const res = await api.utils.tts.speakTest(ttsText.value, false)
    
    // Check res directly (interceptors return response.data)
    if (res.status === 'success' && res.audio_url) {
      ttsStatus.value = 'Playing...'
      const audio = new Audio(api.resolveMediaUrl(res.audio_url))
      await audio.play()
      ttsStatus.value = 'Played successfully'
    } else if (res.status === 'success') {
      const provider = res.result?.provider || 'server TTS'
      ttsStatus.value = `Generated by ${provider}, but no audio URL was provided`
    } else {
      throw new Error(res.result?.message || 'TTS request failed')
    }
    
    setTimeout(() => { ttsStatus.value = null }, 3000)
  } catch (err) {
    const msg = err.response?.data?.detail || err.message || 'Failed to play audio'
    error.value = `Error: ${msg}`
    console.error(err)
  } finally {
    isLoading.value = false
  }
}

// ===================== LIBRARY ACTIONS =====================
const fetchAudioFiles = async () => {
  try {
    isLoading.value = true
    const files = await api.audio.getAll()
    audioFiles.value = files
  } catch (err) {
    console.error('Failed to fetch audio files:', err)
    // Don't set error here to avoid blocking TTS usage if just audio files fail
  } finally {
    isLoading.value = false
  }
}

const playOnGlove = async (filename) => {
  try {
    await api.audio.playESP32(filename)
    toast.add({ severity: 'success', summary: 'Playing on glove', detail: filename, life: 3000 })
  } catch {
    toast.add({ severity: 'error', summary: 'Playback failed', detail: 'Could not play on the glove device.' })
  }
}

const playOnLaptop = async (filename) => {
    try {
        await api.audio.playLaptop(filename)
    } catch {
        toast.add({ severity: 'error', summary: 'Playback failed', detail: 'Could not play on this device.' })
    }
}

// Delete confirmation - holds the filename pending confirmation so the
// destructive action always goes through the shared confirm modal instead
// of a blocking native confirm() dialog.
const deleteTarget = ref(null)
const deleteConfirmOpen = computed(() => !!deleteTarget.value)

const requestDelete = (filename) => {
  deleteTarget.value = filename
}

const cancelDelete = () => {
  deleteTarget.value = null
}

const confirmDelete = async () => {
  const filename = deleteTarget.value
  deleteTarget.value = null
  try {
    await api.audio.delete(filename)
    await fetchAudioFiles()
    toast.add({ severity: 'success', summary: 'File deleted', detail: filename, life: 3000 })
  } catch {
    toast.add({ severity: 'error', summary: 'Delete failed', detail: `Could not delete ${filename}.` })
  }
}

const triggerUpload = () => fileInput.value.click()

const handleFileUpload = async (event) => {
  const file = event.target.files[0]
  if (!file) return
  await uploadFile(file)
}

const onDrop = async (event) => {
  isDragging.value = false
  const file = event.dataTransfer.files[0]
  if (file && file.type.startsWith('audio/')) {
    await uploadFile(file)
  }
}

const uploadFile = async (file) => {
  try {
    isLoading.value = true
    await api.audio.upload(file, 'web-user')
    await fetchAudioFiles()
    toast.add({ severity: 'success', summary: 'File uploaded', detail: file.name, life: 3000 })
  } catch {
    toast.add({ severity: 'error', summary: 'Upload failed', detail: `Could not upload ${file.name}.` })
  } finally {
    isLoading.value = false
  }
}
</script>

<template>
  <div class="space-y-6">
    <!-- Header with Tabs -->
    <BasePageHeader title="Voice Studio" description="Manage audio, speech-to-text, and TTS capabilities.">
      <template #actions>
        <div class="flex bg-slate-900 border border-slate-800 p-1 rounded-lg">
          <button
            v-for="tab in ['tts', 'library', 'live']"
            :key="tab"
            class="px-4 py-2 rounded-md text-sm font-medium transition-colors"
            :class="activeTab === tab ? 'bg-brand-600 text-slate-100' : 'text-slate-400 hover:text-slate-100'"
            @click="activeTab = tab"
          >
            {{ tab === 'tts' ? 'Text to Speech' : tab === 'library' ? 'Audio Library' : 'Live Voice' }}
          </button>
        </div>
      </template>
    </BasePageHeader>

    <!-- Error Alert -->
    <div v-if="error" class="bg-danger-500/10 border border-danger-500/20 text-danger-400 p-4 rounded-lg flex justify-between items-center gap-3">
      <span class="text-sm">{{ error }}</span>
      <button type="button" class="focus-ring icon-btn grid h-7 w-7 shrink-0 place-items-center rounded-md hover:text-slate-100" aria-label="Dismiss error" @click="error = null">
        <PhX size="14" weight="bold" aria-hidden="true" />
      </button>
    </div>

    <!-- ===================== TTS TAB ===================== -->
    <div v-if="activeTab === 'tts'" class="space-y-6">
      <BaseCard>
        <div class="space-y-6">
          <h2 class="text-lg font-semibold tracking-tight text-slate-100">Text to Speech Engine</h2>

          <!-- Engine Selector -->
          <div class="flex flex-wrap items-center gap-4">
            <div class="segmented">
               <button
                 type="button"
                 class="segmented-option"
                 :class="{ 'segmented-option-active': ttsEngine === 'gtts' }"
                 @click="ttsEngine = 'gtts'"
               >
                 GTTS
               </button>
               <button
                 type="button"
                 class="segmented-option"
                 :class="{ 'segmented-option-active': ttsEngine === 'os' }"
                 @click="ttsEngine = 'os'"
               >
                 Device Default
               </button>
            </div>
            <div class="flex items-center gap-1.5 text-xs text-slate-500">
                <PhInfo size="14" aria-hidden="true" />
                {{ ttsEngine === 'gtts' ? 'Runs on the server' : 'Runs on your device' }}
            </div>
          </div>

          <!-- Input Area -->
          <div class="space-y-2">
            <label class="text-sm font-medium text-slate-300">Enter text to speak</label>
            <textarea 
              v-model="ttsText"
              rows="4"
              class="w-full bg-slate-900 border border-slate-700 rounded-lg p-4 text-slate-100 placeholder-slate-600 focus:outline-none focus:border-brand-500 focus:ring-1 focus:ring-brand-500 transition-all resize-none"
              placeholder="Type something here (e.g., 'Hello, how can I help you?')..."
            ></textarea>
          </div>

          <!-- Actions -->
          <div class="flex items-center gap-4">
            <BaseBtn :disabled="!ttsText || isLoading" class="flex items-center gap-2" @click="speakText">
              <PhLaptop size="18" aria-hidden="true" />
              {{ isLoading ? 'Generating...' : 'Play' }}
            </BaseBtn>
            
            <div v-if="ttsStatus" class="text-sm text-brand-300 animate-pulse">
              {{ ttsStatus }}
            </div>
          </div>
        </div>
      </BaseCard>
    </div>

    <!-- ===================== LIBRARY TAB ===================== -->
    <div v-if="activeTab === 'library'" class="space-y-6">
        <!-- New Upload Zone -->
      <div 
        class="border-2 border-dashed rounded-xl p-8 text-center transition-all cursor-pointer group" 
        :class="isDragging ? 'border-brand-500 bg-brand-500/10' : 'border-slate-700 hover:border-brand-500/50 hover:bg-slate-800/50'"
        @dragover.prevent="isDragging = true"
        @dragleave.prevent="isDragging = false"
        @drop.prevent="onDrop"
        @click="triggerUpload"
      >
        <input ref="fileInput" type="file" class="hidden" accept="audio/*" @change="handleFileUpload">
        <div class="flex flex-col items-center gap-3">
          <div class="w-12 h-12 rounded-full bg-slate-800 flex items-center justify-center group-hover:bg-brand-500/20 transition-colors">
            <PhUploadSimple size="24" class="text-slate-400 group-hover:text-brand-300" aria-hidden="true" />
          </div>
          <div>
            <h3 class="font-medium text-slate-100 mb-1">Upload Audio File</h3>
            <p class="text-sm text-slate-500">Drag & drop or click to browse (MP3, WAV)</p>
          </div>
        </div>
      </div>

      <!-- File List -->
      <div v-if="audioFiles.length === 0 && !isLoading" class="text-center py-12">
        <div class="w-16 h-16 bg-slate-800 rounded-full flex items-center justify-center mx-auto mb-4">
            <PhMusicNotes size="32" class="text-slate-500" aria-hidden="true" />
        </div>
        <h3 class="text-lg font-medium text-slate-100 mb-1">No audio files found</h3>
        <p class="text-slate-500">Upload a file to get started</p>
      </div>

      <div v-else class="grid grid-cols-1 gap-4">
        <BaseCard v-for="file in filteredFiles" :key="file.filename" class="group hover:border-brand-400/30 transition-colors">
          <div class="flex items-center justify-between">
            <div class="flex items-center gap-4">
              <div class="w-10 h-10 rounded-lg bg-brand-500/10 flex items-center justify-center text-brand-300">
                <PhFileAudio size="20" aria-hidden="true" />
              </div>
              <div>
                <h3 class="font-medium text-slate-100 group-hover:text-brand-200 transition-colors">{{ file.filename }}</h3>
                <div class="text-xs text-slate-500 flex items-center gap-2">
                  <span>{{ new Date(file.upload_time).toLocaleDateString() }}</span>
                  <span>•</span>
                  <span>{{ (file.size / 1024 / 1024).toFixed(2) }} MB</span> <!-- Mock size if not real -->
                </div>
              </div>
            </div>
            
            <div class="flex items-center gap-2">
              <button type="button" class="focus-ring p-2 rounded-lg hover:bg-brand-500/20 text-slate-400 hover:text-brand-300 transition-colors" title="Play on Glove" :aria-label="`Play ${file.filename} on glove`" @click="playOnGlove(file.filename)">
                <PhSpeakerHigh size="20" aria-hidden="true" />
              </button>
              <button type="button" class="focus-ring p-2 rounded-lg hover:bg-brand-500/20 text-slate-400 hover:text-brand-300 transition-colors" title="Play on Laptop" :aria-label="`Play ${file.filename} on laptop`" @click="playOnLaptop(file.filename)">
                <PhLaptop size="20" aria-hidden="true" />
              </button>
              <button type="button" class="focus-ring p-2 rounded-lg hover:bg-danger-500/20 text-slate-400 hover:text-danger-400 transition-colors" title="Delete" :aria-label="`Delete ${file.filename}`" @click="requestDelete(file.filename)">
                <PhTrash size="20" aria-hidden="true" />
              </button>
            </div>
          </div>
        </BaseCard>
      </div>
    </div>

    <!-- ===================== LIVE VOICE TAB (Placeholder) ===================== -->
    <div v-if="activeTab === 'live'" class="text-center py-20">
      <div class="w-20 h-20 bg-slate-800 rounded-full flex items-center justify-center mx-auto mb-6">
        <PhMicrophone size="40" class="text-slate-500" aria-hidden="true" />
      </div>
      <h2 class="text-xl font-bold text-slate-100 mb-2">Live Speech Recognition</h2>
      <p class="text-slate-400 max-w-md mx-auto">
        This feature will allow you to stream audio from your microphone directly to the backend for real-time transcription.
      </p>
      <BaseBtn variant="secondary" class="mt-6" disabled>Coming Soon</BaseBtn>
    </div>

    <BaseModal
      :model-value="deleteConfirmOpen"
      title="Delete audio file"
      @update:model-value="(v) => !v && cancelDelete()"
    >
      <p class="text-sm text-slate-300">
        Delete <span class="font-semibold text-slate-100">{{ deleteTarget }}</span>? This can't be undone.
      </p>

      <template #footer>
        <BaseBtn variant="secondary" @click="cancelDelete">Cancel</BaseBtn>
        <BaseBtn variant="danger" @click="confirmDelete">Delete</BaseBtn>
      </template>
    </BaseModal>

  </div>
</template>
